version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./generate.ddl:/docker-entrypoint-initdb.d/generate.sql
    ports:
      - 55432:5432
      - 8000:8000
    stdin_open: true
    tty: true

  go_application:
    image: go_application
    networks: []

