version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 55432:5432

  go_application:
    build:
      context: .
      dockerfile: Dockerfile
    image: go_application
    ports:
      - 5050:5050
    stdin_open: true
    tty: true
