// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package queries

import (
	"database/sql"
	"time"
)

type Amministratore struct {
	Idmembro int32
}

type Chat struct {
	Nome        string
	Descrizione string
	Idchat      int32
}

type Contenuto struct {
	Autore                 string
	Testo                  string
	Idcontenuto            string
	Timestamppubblicazione time.Time
	Titolo                 sql.NullString
	Idregione              sql.NullInt32
	Usernamepadre          sql.NullString
	Idcontenutopadre       sql.NullString
}

type Membro struct {
	Dataentrata    time.Time
	Idmembro       int32
	Username       string
	Idchat         int32
	Amministratore sql.NullInt32
}

type Messaggio struct {
	Idmessaggio               int32
	Testo                     string
	Timestampinvio            time.Time
	Mittente                  int32
	Citazione                 sql.NullInt32
	Autorecontenuto           sql.NullString
	Idcontenuto               sql.NullString
	Amministratoreeliminatore sql.NullInt32
}

type Reazione struct {
	Autorecontenuto string
	Idcontenuto     string
	Username        string
	Likedislike     string
	Timestamp       string
}

type Regione struct {
	Idregione    int32
	Nome         string
	Superregione sql.NullInt32
}

type Seguire struct {
	Usernameseguace string
	Usernameseguito string
	Datainizio      time.Time
	Datafine        sql.NullTime
}

type StoricoAccesso struct {
	Username        string
	Timestamplogin  time.Time
	Timestamplogout time.Time
}

type StoricoPassword struct {
	Username        string
	Datainserimento time.Time
	Password        string
}

type Uscitum struct {
	Idmembro             int32
	Datauscita           time.Time
	Motivazione          sql.NullString
	Idmembroresponsabile sql.NullInt32
}

type Utente struct {
	Username      string
	Datadinascita sql.NullTime
	Nome          sql.NullString
	Cognome       sql.NullString
	Domicilio     sql.NullInt32
}
