// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package queries

import (
	"context"
)

const something = `-- name: Something :one
SELECT nome, descrizione, idchat FROM CHAT
`

func (q *Queries) Something(ctx context.Context) (Chat, error) {
	row := q.db.QueryRowContext(ctx, something)
	var i Chat
	err := row.Scan(&i.Nome, &i.Descrizione, &i.Idchat)
	return i, err
}
